# Generated by Django 5.2.7 on 2025-10-30 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254, unique=True, verbose_name='メールアドレス'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='正しい電話番号形式で入力してください。（例: 090-1234-5678 または 09012345678）', regex='^(0\\d{1,4}-?\\d{1,4}-?\\d{4}|0\\d{9,10})$')], verbose_name='電話番号'),
        ),
    ]
