# Generated by Django 5.2.7 on 2025-11-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_customer', models.BooleanField(default=True, verbose_name='顧客編集権限')),
                ('can_delete_customer', models.BooleanField(default=True, verbose_name='顧客削除権限')),
                ('can_edit_reservation', models.BooleanField(default=True, verbose_name='予約編集権限')),
                ('can_delete_reservation', models.BooleanField(default=True, verbose_name='予約削除権限')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='main.administrator')),
            ],
            options={
                'verbose_name': 'ユーザー権限',
                'verbose_name_plural': 'ユーザー権限',
            },
        ),
    ]
