# Generated by Django 5.2.7 on 2025-11-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_delete_customer',
            field=models.BooleanField(default=False, verbose_name='顧客削除権限'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_delete_reservation',
            field=models.BooleanField(default=False, verbose_name='予約削除権限'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_edit_customer',
            field=models.BooleanField(default=False, verbose_name='顧客編集権限'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_edit_reservation',
            field=models.BooleanField(default=False, verbose_name='予約編集権限'),
        ),
    ]
