# Generated by Django 5.2.7 on 2025-10-31 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customer_email_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='正しい電話番号形式で入力してください。（例: 090-1234-5678、03-1234-5678、0120-123-456）', regex='^0\\d{1,4}-?\\d{1,4}-?\\d{3,4}$')], verbose_name='電話番号'),
        ),
    ]
