# Generated by Django 5.2.7 on 2025-11-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_can_delete_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='reference_images/', verbose_name='参考画像'),
        ),
    ]
