# Generated by Django 5.2.7 on 2025-11-15 16:36

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reservation_reference_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[main.models.validate_phone_number], verbose_name='電話番号'),
        ),
    ]
