# Generated by Django 5.2.7 on 2025-11-16 15:20

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='reference_images/', validators=[main.models.validate_image_extension], verbose_name='参考画像'),
        ),
    ]
